### ISSUE TITLE
bitcoin.conf and lnd.conf not created on startup

### ISSUE THREAD

**Issue by mikeghen** [crypdex/blackbox#17]
Here is my blackbox.yml:
```
version: '3.7'

services:
  lnd_bitcoin:
```
here is blackboxd version:
```
root@sparkswap:~# blackboxd version
0.1.51
```
here is blackboxd info:
```
root@sparkswap:~# blackboxd info
❯ BLACKBOX config:
services:
  bitcoin:
    command: -rpcuser=xxxx -rpcpassword=xxxx -rpcallowip=0.0.0.0/0 -zmqpubrawblock=tcp://0.0.0.0:28333
      -zmqpubrawtx=tcp://0.0.0.0:28334 -printtoconsole -txindex
    container_name: bitcoind
    environment:
      BITCOIN_NETWORK: testnet
    image: crypdex/bitcoin:0.17
    ports:
    - published: 8332
      target: 8332
    - published: 8333
      target: 8333
    - published: 18332
      target: 18332
    - published: 18333
      target: 18333
    - published: 18443
      target: 18443
    - published: 18444
      target: 18444
    restart: on-failure
    volumes:
    - /mnt/data/friendfund/bitcoin:/home/bitcoin/.bitcoin:rw
  lnd_bitcoin:
    command: --rpclisten=0.0.0.0:10009
    container_name: lnd_bitcoin
    depends_on:
    - bitcoin
    environment:
      BACKEND: bitcoind
      BITCOIN_RPCPASS: xxxx
      BITCOIN_RPCUSER: xxxx
      CHAIN: bitcoin
      NETWORK: testnet
    image: crypdex/lnd:0.6
    restart: on-failure
    volumes:
    - /mnt/data/friendfund/lnd:/home/lnd/.lnd:rw
version: '3.7'
```
On start the `bitcoin.conf` and `lnd.conf` are not created. I expect they would be created  and would have the `.env` variables I've added. As a work around, I just add these files manually for now.
